---
- name: Install Apache, MySQL, PHP 8.2 with Laravel extensions and NVM
  hosts: localhost
  become: yes

  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Add ondrej/php repository
      apt_repository:
        repo: ppa:ondrej/php
        state: present

    - name: Update apt cache after adding ondrej/php
      apt:
        update_cache: yes

    - name: Install Apache
      apt:
        name: apache2
        state: present

    - name: Enable Apache mod_rewrite
      command: a2enmod rewrite
      notify:
        - Restart Apache

    - name: Install MySQL server
      apt:
        name: mysql-server
        state: present

    - name: Install PHP 8.2 and extensions for Laravel
      apt:
        name:
          - php8.2
          - php8.2-cli
          - php8.2-fpm
          - php8.2-mysql
          - php8.2-xml
          - php8.2-mbstring
          - php8.2-zip
          - php8.2-curl
          - php8.2-gd
          - php8.2-bcmath
          - php8.2-tokenizer
          - php8.2-intl
          - libapache2-mod-php8.2
        state: present

    - name: Install Composer using apt
      apt:
        name: composer
        state: present

    - name: Install NVM
      shell: curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.40.1/install.sh | bash
      args:
        creates: "{{ ansible_env.HOME }}/.nvm"

    - name: Set NVM environment variables
      shell: |
        export NVM_DIR="$([ -z "${XDG_CONFIG_HOME-}" ] && printf %s "${HOME}/.nvm" || printf %s "${XDG_CONFIG_HOME}/nvm")"
        [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
      args:
        executable: /bin/bash

    - name: Add NVM environment variables to profile
      lineinfile:
        path: ~/.bashrc
        line: |
          export NVM_DIR="$([ -z "${XDG_CONFIG_HOME-}" ] && printf %s "${HOME}/.nvm" || printf %s "${XDG_CONFIG_HOME}/nvm")"
          [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh" # This loads nvm
        create: yes

    - name: Restart Apache
      service:
        name: apache2
        state: restarted

  handlers:
    - name: Restart Apache
      service:
        name: apache2
        state: restarted
